### ISSUE TITLE
Provide multilingual support

### ISSUE THREAD

**Issue by francescomosca** [theJayTea/WritingTools#1]
The "option_prompts" could be updated with a language reference.
Es. "_In Italian, rewrite this: [...]_"
Or maybe per-language prompts.

Of course an option for this in the settings window is needed.

**Comment by theJayTea** [comment]
Hi, thanks so much for the suggestion :)
The good news is that if you use it on text in another language, it should already work fine and respond with the appropriately changed text in that language.
In the future, when I get time, I'll try adding proper localization.

**Comment by theJayTea** [comment]
That's an interesting idea, but I'm not sure if it would be great here:
- If the model's prompt is accidentally changed to not include the error code output, some functionality will break.
- The prompts for all the buttons are already extensively tested and optimised for the best results
- There already exists a custom instructions box
Thanks for the suggestion, though!

Also, I've fixed the original issue:

**Comment by theJayTea** [comment]
I've fixed this in the latest update (v2) by adding this to the system prompts:
`Respond in the same language as the input (e.g., English US, French).`
