### ISSUE TITLE
The setting UX glitches when moved or resized on a laptop screen

### ISSUE THREAD

**Issue by apoapostolov** [theJayTea/WritingTools#12]
Seems to be only usable when it is not initially moved or when resized to half screen, but then immediately glitches if moved. Seems to be the code for resizing the screen requires minimum size that laptops of 15" do not offer. 

![image](https://github.com/user-attachments/assets/80ab3567-55bb-4804-abe5-2f11fb467c30)

**Comment by theJayTea** [comment]
Whoa, sorry about that! Does pressing `Windows + Up Arrow` to make it full screen make it usable?

**Comment by apoapostolov** [comment]
I think you can solve this by adding tabs and breaking the settings into at least couple tabs to avoid the issue where all the settings are on a single list that will always be larger than 14"+ inch laptops.

**Comment by theJayTea** [comment]
I think just making the large logo smaller (and to the side) may fix this. This is something I'll work on when I get time, but if you can, feel free to contribute with a pull request!

**Comment by theJayTea** [comment]
Fixed with v4!
