### ISSUE TITLE
[Epic] Screenshot a portion of screen to provide to 40 and other multimodal AI along with the selected text. 

### ISSUE THREAD

**Issue by apoapostolov** [theJayTea/WritingTools#14]
A button next to the custom prompt that allows to screenshot a portion of the screen to provide additionally to multimodal AI like 4e or Gemini to get extended prompt functionality.

**Comment by theJayTea** [comment]
The thing is that Writing Tools, fundamentally, is built to work for you and help you with whatever's going on in one textbox.

While I may add a pop-up UI for the summarise feature's result (so you can use it on webpages), this to me seems a little out of scope for this focused tool.

Again, I'll leave this open to hear other opinions on this.

**Comment by theJayTea** [comment]
Again, after additional consideration, I think this would be out of scope for Writing Tools. 
It's not built to replace/act as a general purpose chatbot, but rather to help you with your needs within any textbox.
An additional consideration would be that most local multimodal models wouldn't fit in the majority of users' VRAM.
With that said, thank you again for sharing your idea.
