### ISSUE TITLE
Couldn't build proto file into descriptor pool error 

### ISSUE THREAD

**Issue by Joaov41** [theJayTea/WritingTools#18]
Getting this on MacOS

**Comment by momokrono** [comment]
Hello, could you give us more info? Like, python version, if you are running inside a virtual-env?

Have you tried uninstalling and reinstalling protobuf as suggested [here?](https://stackoverflow.com/questions/68952308/tensorflow-couldnt-build-proto-file-into-descriptor-pool/69081889#69081889)

**Comment by Joaov41** [comment]
Yes I was able to fix that error. Now the app runs, I see the onboarding and get the menu-bar icon, but the key shortcut doesn't work and python crashes.
On Mac , using python 3.10 now, on a conda environment.

**Comment by theJayTea** [comment]
Hi @Joaov41 ! Have you tried running the builds in the macOS folder?
That has been built for and tested on macOS by @kurcz .
It's still early stages.

**Comment by Joaov41** [comment]
Yes, this error happens running the macOS build.
I will try the universal build.

**Comment by theJayTea** [comment]
Closing this as there's now a new, native Swift macOS version maintained by @Aryamirsepasi :D
