### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by cynical2010** [theJayTea/WritingTools#19]
![image](https://github.com/user-attachments/assets/e4e008d3-3803-45f3-9ab3-2f1c3f7b06f8)

can't connect after update to V4.

![image](https://github.com/user-attachments/assets/2d0d9112-f20f-4594-8efa-557ebf18495b)

**Comment by cynical2010** [comment]
![image](https://github.com/user-attachments/assets/fcf79737-d283-4f23-83ce-bebb09a4ebd1)

please change the instructions for loading in the settings, as it is not mentioned there that you have to enter “KoboldCPP” as the API key to establish a connection

**Comment by theJayTea** [comment]
Hey @cynical2010, I'm glad you got it fixed.

The exact dud API key (and base URL) to use will depend on your local LLM platform — there are _numerous_, and it wouldn't be feasible for Writing Tools to maintain documentation for each. Refer to the platform's documentation for this.

Also PS, I think you're still on v3 in that first screenshot, as v4 modified the Settings UI to make it fit better on smaller screens and not clip.

Cheers!

**Comment by cynical2010** [comment]
thanks for your reply, i'm a bit late and have only just looked through my inbox, but i'm now on the latest version and it's working great.
Is it possible to customize the tokens to be used when I make a summary of say a long text on wiki or so.... it would be great to have some kind of slider where I could quickly increase the tokens?
somehow not hardcode the json? i don't know the programming stuff but i think this is done via the json or some kind of config or?

**Comment by theJayTea** [comment]
Hi @cynical2010 , glad you got it working now.

A slider like that won't be possible.
The way LLMs work, there isn't a parameter in the API call to control how long their response should be crafted to. There's only a max token limit (set to the default highest level), which just stops/truncates the responses at that point.

In your case, simply select the text, and use the `Describe your change` box to ask for a "short summary" or a "long summary" or even a "100 word summary" :)

**Comment by cynical2010** [comment]
✅ hey, hey @theJayTea, ✅

Yes, that makes total sense now that you write it, thanks again. I had two different things in my head with my previous text. I was thinking of the context slider, but that is for the context and not for the output length. But I'll try it out, thanks again for your answer.
