### ISSUE TITLE
System Tray Popup

### ISSUE THREAD

**Issue by Disneyhockey40** [theJayTea/WritingTools#2]
I'm using Windows 11 Pro, build 22631.4317, with dark mode enabled. When I right-click on WritingTools, the popup menu has a black background and black text, making it difficult to read.

**Comment by theJayTea** [comment]
Thank you for bringing this up! Ah, the perks of developing it mostly in light mode haha.

QT 6, which is what Writing Tools uses for its UI, seems to automatically try and theme elements to the dark theme.

I've preliminarily tried to opt-out of this (all the code at the end of `main.py` tries to achieve this), but I haven't done so perfectly.

I'll look into this further when I get time, and I welcome contributions from others too :)

**Comment by theJayTea** [comment]
Fixed in V2 with your contributions :D

**Comment by theJayTea** [comment]
Fixed in V2 with your contributions :D
Thank you.
