### ISSUE TITLE
Icons shouldn't need to be stored separately

### ISSUE THREAD

**Issue by user1823** [theJayTea/WritingTools#21]
Currently, if I don't keep the icon pngs along with the exe file, the dialogs don't show the icons. This is not desirable. The .exe should have the icons embedded.

**Comment by theJayTea** [comment]
Hi. I'll embed the app icon with the next update, but I wanted to keep customization of the icons and especially the background image open.

People have already shared their own icon sets and stuff.

**Comment by user1823** [comment]
Atleast the send icon for the "describe your change" box should be embedded.

**Comment by theJayTea** [comment]
I actually would prefer the existing implementation of separate icons, just to allow users as much customisability as possible.

Custom button icons would also be required for customisable button options planned for the future.

Thanks for your suggestions though.
