### ISSUE TITLE
Fullscreen settings display bug

### ISSUE THREAD

**Issue by jangroeschel** [theJayTea/WritingTools#32]
Love the project! Just noticed that when trying to change the settings while trying different ollama local models that the model name and URL fields disappeared below the screen on my small 14 inch Windows 11 laptop screen. Made it quite difficult to change the settings.

**Comment by theJayTea** [comment]
Whoops! I'll have to further optimize the UI of the settings page, it doesn't help that I made this on my 32-inch monitor haha.

As a temporary workaround, you could press `Windows + Up Arrow` with the window in focus and it'll go to full screen, making things visible

**Comment by jangroeschel** [comment]
Nice idea but this still doesn't show me a scroll bar to change the model settings. Only workaround on small screen for me seems to be to go back to non-full screen view and then drag up until I can see the lower part of the settings screen. 

Screenshot attached for reference :)
<img width="956" alt="Screenshot 2024-11-01 110456" src="https://github.com/user-attachments/assets/7d573cbd-1c0a-41c5-9797-a94267c1cbde">

**Comment by theJayTea** [comment]
Thanks for bringing this up. I’ll work on improving this soon!

**Comment by theJayTea** [comment]
The settings UI is improved in this version with its own scroll bar and intelligent window height logic (according to display height). I think I even forgot to add this to the changelog haha
