### ISSUE TITLE
error with binary missing libraries

### ISSUE THREAD

**Issue by prietus** [theJayTea/WritingTools#34]
building from source on linux (arch linux) 
python pyinstaller-build-script.py 
the resultant binay fails to launch with 
`ist/Writing\ Tools 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from WritingToolApp import WritingToolApp
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "WritingToolApp.py", line 16, in <module>
    from aiprovider import Gemini15FlashProvider, OpenAICompatibleProvider
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "aiprovider.py", line 6, in <module>
    import google.generativeai as genai
ModuleNotFoundError: No module named 'google'
[PYI-78365:ERROR] Failed to execute script 'main' due to unhandled exception!
` thanks in advance

**Comment by theJayTea** [comment]
Hi! Have you installed all the requirements with `pip install -r requirements. txt`? It looks like `google-generativeai` isn't installed.

**Comment by prietus** [comment]
hello, yes I did

**Comment by momokrono** [comment]
Hi, I'm on arch as well, so I hope I can help you with this. Do you have the same problem if you run the main.py script? Do you use a virtual env?

**Comment by prietus** [comment]
Hello. No I don’t have the error when I run main.py. And yes I do have a virtual env. Btw on arch how do you make keybinds to work?
Regards.
Carlos Prieto

El 4 nov 2024, a las 21:36, momokrono ***@***.***> escribió:

﻿

Hi, I'm on arch as well, so I hope I can help you with this. Do you have the same problem if you run the main.py script? Do you use a virtual env?

**Comment by momokrono** [comment]
Hi, sorry for the late reply but I'm extremely busy these days.

If you are on Wayland, the app will not work. Wayland by default doesn't allow apps not in focus to listen to keypresses, so if you want the app to work you need to login with an X-session of whatever desktop environment you have.
In your login window (and this is true whether you use GDM, SDDM, LightDM, whatever), you should see a menu where you will have different entries for your desktop environment and you can select what type of session to log into. Be sure to select something like "\<your DE\> on X", "\<DE\> legacy" or something like this. If you knew all this, sorry to sound condescending. I didn't want to sound like the average RTFM arch-dude, but hopefully this helps other people reading this.

For me, Wayland is a must have, so I am able to use the app only with all apps running through Xwayland, like my IDE, my note editor and so on. If you run apps through Xwayland, the shortcut will work. If you want to know what apps are running through Xwayland you can run `xlsclients` in your terminal. You can install the package via `pacman -S xorg-xlsclients`.
I know, it's less than ideal but as soon as I have some free time I plan to solve this problem. Most likely by finding a way to add a global shortcut or by creating a guide where you can setup a shortcut inside your DE. For now there is not much I can do.

About the binary missing a library: weird, I'm not able to reproduce the problem on my side, but again I'll try to better help you once I'll have a bit more free time.

Just as a note, I plan on creating a flatpak/appimage and uploading the package to the AUR. Again, once I'll have time to dedicate to this project.

**Comment by prietus** [comment]
Tyvm for the explanation
Carlos Prieto

El 7 nov 2024, a las 9:41, momokrono ***@***.***> escribió:

﻿

Hi, sorry for the late reply but I'm extremely busy these days.

If you are on Wayland, the app will not work. Wayland by default doesn't allow apps not in focus to listen to keypresses, so if you want the app to work you need to login with an X-session of whatever desktop environment you have.
In your login window (and this is true whether you use GDM, SDDM, LightDM, whatever), you should see a menu where you will have different entries for your desktop environment and you can select what type of session to log into. Be sure to select something like "<your DE> on X", "<DE> legacy" or something like this. If you knew all this, sorry to sound condescending. I didn't want to sound like the average RTFM arch-dude, but hopefully this helps other people reading this.

For me, Wayland is a must have, so I am able to use the app only with all apps running through Xwayland, like my IDE, my note editor and so on. If you run apps through Xwayland, the shortcut will work. If you want to know what apps are running through Xwayland you can run xlsclients in your terminal. You can install the package via pacman -S xorg-xlsclients.
I know, it's less than ideal but as soon as I have some free time I plan to solve this problem. Most likely by finding a way to add a global shortcut or by creating a guide where you can setup a shortcut inside your DE. For now there is not much I can do.

About the binary missing a library: weird, I'm not able to reproduce the problem on my side, but again I'll try to better help you once I'll have a bit more free time.

Just as a note, I plan on creating a flatpak/appimage and uploading the package to the AUR. Again, once I'll have time to dedicate to this project.

**Comment by theJayTea** [comment]
Thanks for helping out, @momokrono ! It looks like this specific issue is resolved, maybe we can add that note about the DE into the README in the future.
