### ISSUE TITLE
encounter a new issue, the codes are listed below!

### ISSUE THREAD

**Issue by WYang555** [theJayTea/WritingTools#37]
2024-11-04 23:33:46,725 - ERROR - Unhandled exception in listener callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pynput/_util/darwin.py", line 283, in _handler
    self._handle(proxy, event_type, event, refcon)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable

**Comment by momokrono** [comment]
Hi!
What platform are you running on? Did you install everything in a virtual env?

**Comment by WYang555** [comment]
no i directly run it on macos, i also installed all dependency using python3.13, but it reported errors.

**Comment by WYang555** [comment]
> Hi! 你好！ What platform are you running on? Did you install everything in a virtual env?您在哪个平台上运行？您是否在虚拟环境中安装了所有内容？

necessary to install everything i a virtual env?

**Comment by WYang555** [comment]
> > Hi! 你好！ What platform are you running on? Did you install everything in a virtual env?您在哪个平台上运行？您是否在虚拟环境中安装了所有内容？
> 
> necessary to install everything i a virtual env?

the chip is M series

**Comment by WYang555** [comment]
i run these codes in python 3.12, but the bug reports that the""SafetySettingDict" is missing. where can i find the new version of google--generativeai? thank you!
  File "main.py", line 3, in <module>
    from WritingToolApp import WritingToolApp
  File "/Users/wangyang/Desktop/WritingTools-main/macOS/WritingToolApp.py", line 17, in <module>
    from google.generativeai.types import SafetySettingDict
ImportError: cannot import name 'SafetySettingDict' from 'google.generativeai.types' (/Users/wangyang/Library/Python/3.8/lib/python/site-packages/google/generativeai/types/__init__.py)

**Comment by theJayTea** [comment]
@WYang555 try `pip install --upgrade google-generativeai`

**Comment by WYang555** [comment]
i did, but it reported the same bug

**Comment by WYang555** [comment]
thank you for all your efforts, the new version is anticipated

**Comment by theJayTea** [comment]
Closing this as there's now a new, native Swift macOS version maintained by @Aryamirsepasi :D
Installation instructions will come soon.
