### ISSUE TITLE
Add Ollama support 

### ISSUE THREAD

**Issue by NurvX** [theJayTea/WritingTools#4]
Would be great to add ollama support, local models will add to privacy.

**Comment by theJayTea** [comment]
This is something that's in the works for the future :D

**Comment by theJayTea** [comment]
The latest update adds support for a multitude of local LLMs via Ollama, llama.cpp, KoboldCPP, TabbyAPI, vLLM, etc.

Any OpenAI-Compatible API will work!

For Ollama specifically, check out:
https://ollama.com/blog/openai-compatibility

Keep in mind that Ollama's OpenAI-Compatible API is experimental, so the other platforms may be a better option.
