### ISSUE TITLE
macos version is not working

### ISSUE THREAD

**Issue by mrczorz** [theJayTea/WritingTools#44]
i cant get it to work. provide better instructions for it to work. because i followed all your instructions. when the script starts and i press the shortcut i setup. i tried fixing it with ai didnt work too. so tell us how to install it on macos

**Comment by theJayTea** [comment]
Hi @mrczorz , as noted on the folder name, unfortunately the macOS version is not (currently) actively maintained.

@kurcz handled the build, and while he may be able to help adapt the current v5 Windows & Linux build to macOS, it'll depend on whether he has the bandwidth to help out with it.

For now, I don't have access to a macOS device myself to debug it (my Hackintosh physically broke :')

Best,
Jesai

**Comment by theJayTea** [comment]
Hi @mrczorz , as noted on the folder name, unfortunately the macOS version is not (currently) actively maintained.

@kurcz handled the build, and while he may be able to help adapt the current v5 Windows & Linux build to macOS, it'll depend on whether he has the bandwidth to help out with it.

For now, I don't have access to a macOS device myself to debug it (my Hackintosh physically broke :')

Best,
Jesai
