### ISSUE TITLE
No option for ollama

### ISSUE THREAD

**Issue by MeNicefellow** [theJayTea/WritingTools#45]
![image](https://github.com/user-attachments/assets/6bf9e0b8-ac6a-4d71-999e-68b69dbfede9)
Only Gemini and OpenAI compatible. But in your README, you said it supports ollama?

**Comment by theJayTea** [comment]
Hello!

Ollama is supported through its OpenAI comparable API.

The README has detailed step-by-step instructions on how to connect Writing Tools to Ollama — it'll take just a minute.

Once you complete this, the next time you reboot your PC, you simply have to launch both programs into the background and things will just work without any additional setup!

![Screenshot_20241120-203052_Chrome](https://github.com/user-attachments/assets/e9e0b3d0-6afe-4bfa-9b7a-dabee6e6577a)
