### ISSUE TITLE
Windows arm64 builds

### ISSUE THREAD

**Issue by minzdrav** [theJayTea/WritingTools#55]
Hi @theJayTea 
One of my devices is an arm64 laptop with Windows 11 and WritingTools is working fine on the emulation layer.
But it's always better to have a native version.
If your framework supports arm builds, please release a native arm64 version.

**Comment by theJayTea** [comment]
For context, we're using PyInstaller to compile the distributable .exe.

It doesn't look like I can compile for ARM without running PyInstaller on an ARM device.

I do not have access to an ARM Windows device, but I will research more if cross-compilation is somehow doable.

I'll close this issue for now as it's not something I can immediately (or probably ever) address, but rest assured that I will research more into this in the future and open the issue if it ends up being possible.

**Comment by minzdrav** [comment]
Guide to run on Windows ARM64 nativly:
1. Download sources
2. Download ARM64 python installer: https://www.python.org/downloads/windows/ 
3. Open Windows_and_Linux in the terminal
4. pip install -r requirements.txt
5. pythonw main.py

Step 4 failed with the following error:
ERROR: Could not find a version that satisfies the requirement PySide6 (from versions: none)

So, right now it is not possible to build a native version. However, it will be possible in the future :)
![image](https://github.com/user-attachments/assets/9174bbef-7dbd-4138-9e76-f2a7a6c2a00f)
