### ISSUE TITLE
Custom Instructions

### ISSUE THREAD

**Issue by Raynbda** [theJayTea/WritingTools#56]
I want to be able to give writing tools a set of guidelines to follow whenever i ask it to follow them or by adding these guidelines as a separate custom button. For example, i want it to give it the everything search syntax once https://www.voidtools.com/support/everything/searching/ and make it write a search prompt that works with everything search whenever i ask something like "find files modified this week, under 5mb of type png using everything search" for example

**Comment by theJayTea** [comment]
This is in the roadmap for the future :)

**Comment by theJayTea** [comment]
Hi! This will be out in the next update. With the latest release, I focused on other features and bug fixes. I’m closing this issue as it's essentially a repeat of https://github.com/theJayTea/WritingTools/issues/38 . Rest assured that this will come soon :D
