### ISSUE TITLE
Add a custom command button.

### ISSUE THREAD

**Issue by Syed1337** [theJayTea/WritingTools#64]
I request a feature to add custom command buttons.  Users should be able to add their own prompts, such as translating text between languages or retrieving text in a specific format.

**Comment by theJayTea** [comment]
This is coming in the next Win/Linux update :D 
It'll be out in ~2 weeks - I have exams right now again, so apologies for the delay.

**Comment by Nisekoi-1** [comment]
I was going to request the same; good to know you are working on it.

**Comment by theJayTea** [comment]
Hi! This will be out in the next update. With the latest release, I focused on other features and bug fixes. I’m closing this issue as it's a repeat of #38 . Rest assured that this will come soon :D
