### ISSUE TITLE
Alternate Mac version / IOS port

### ISSUE THREAD

**Issue by Joaov41** [theJayTea/WritingTools#66]
I have an alternate version of this code for Mac, which implements a Q&A, so after the selecting any of the options, one can ask questions to the LLM about the context passed, which allows for a bit more versatility. 

I have also ported to IOS.  If anyone interested.

**Comment by ErrorCatDev** [comment]
Sounds interesting. I'm really curious to know how you port it to ios. Did you develop an extension to replace the keyboard or is it a standalone app?

**Comment by Joaov41** [comment]
> Sounds interesting. I'm really curious to know how you port it to ios. Did you develop an extension to replace the keyboard or is it a standalone app?

It is a standalone app. The UI is minimal (design is not my specialty). It has a share sheet extension to pass the selected text to the app, and from there on, it is just like the Mac app. I also incorporated an option to paste clipboard content as input to the LLM, as this is sometimes useful. The only problem with using the share sheet is that it requires the app group to be assigned on the developer portal, so, installation is not user-friendly for those without a developer account. But your idea of an extension is a great one. I hadn't thought of that.

**Comment by ErrorCatDev** [comment]
> It is a standalone app. The UI is minimal (design is not my specialty). It has a share sheet extension to pass the selected text to the app, and from there on, it is just like the Mac app. I also incorporated an option to paste clipboard content as input to the LLM, as this is sometimes useful. The only problem with using the share sheet is that it requires the app group to be assigned on the developer portal, so, installation is not user-friendly for those without a developer account. But your idea of an extension is a great one. I hadn't thought of that.

Seems interesting! Looks like what you have built could potentially be a better alternative to Apple's writing tools. But, like you said, Apple's requirements for developer accounts may hinder installation. Nevertheless, I'm really interested in trying it out. Would you be willing to share the source code here?

**Comment by theJayTea** [comment]
Hi @Joaov41 , interesting! I love that you have an iOS version. Feel free to get inspired by our work around here.

We’ve actually already built a Q&A-esque feature that’s coming to the next macOS and Windows updates this week, which lets you ask a follow-up question to the summary window.

All the best with your build!

**Comment by theJayTea** [comment]
Hi @Joaov41 , interesting! I love that you have an iOS version. Feel free to get inspired by our work around here.

We’ve actually already built a Q&A-esque feature that’s coming to the next macOS and Windows updates this week, which lets you ask a follow-up question to the summary window.

If you’d like to discuss things further or share the code with ErrorCatDev, please feel free to re-open this issue.

All the best with your build! You can always reach out if you’d ever want advice or feedback with anything.

**Comment by Joaov41** [comment]
> Hi @Joaov41 , interesting! I love that you have an iOS version. Feel free to get inspired by our work around here.
> 
> We’ve actually already built a Q&A-esque feature that’s coming to the next macOS and Windows updates this week, which lets you ask a follow-up question to the summary window.
> 
> If you’d like to discuss things further or share the code with ErrorCatDev, please feel free to re-open this issue.
> 
> All the best with your build! You can always reach out if you’d ever want advice or feedback with anything.

Here is the IOS port for iPhone : https://github.com/Joaov41/tools
I also have an Ipad version, but that version , using Stage Manager has a weird delay updating the shared content. Tried to mitigate forcing more frequent update of the app status, but that resulting in huge CPU and battery usage, so work in progress still. 

I see that as of today the windows version already has the q&a feature, the Mac still doesn't but since it is on its way, no need to share my version with that feature.
