### ISSUE TITLE
missing "Start on Boot" toggle

### ISSUE THREAD

**Issue by sasagr** [theJayTea/WritingTools#76]
Fantastic job on the v6 for Windows
However I don't see the "Start on Boot" toggle in Settings

**Comment by theJayTea** [comment]
Hello, thanks for the kind words :)
The start on boot option does not show up if you run it from source with the terminal.
It only shows up when it's running on the compiled exe (as the option needs to set the executable to start on boot in the registry).

**Comment by sasagr** [comment]
oh.. you are right! I m actually running it from terminal. I m doing this because I wanted to try to modify part of the code to achieve https://github.com/theJayTea/WritingTools/issues/77 and actually achieved it. It was enough to add the other cases in a couple of lines

**Comment by theJayTea** [comment]
Ah, that’s cool! About #77 - I’ll also be officially implementing customisation for that in the next version :)
Cheers!
