### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by beenycool** [theJayTea/WritingTools#78]
Hello,
I have just downloaded this as a replacement to the absolute garbage of Grammarly. I love how it is privacy based, and the ui looks amazing! Just a couple of feature requests:
1) For instant things that doesn't bring up the window, (like proofread) can you show the difference it has made? This will be especially useful for large documents.
2) Say if I want to switch from Ollama to Gemini for larger/more complicated files, it is a bit of a pain to delete config.json and do all of the setup again. It would be nice on the UI to change what AI we use?
3) I want to use System Prompts to help me with my work,.
Thanks!

**Comment by theJayTea** [comment]
Hello! Thank you for the kind words! 

1. That’s something I’m looking into adding :D 

2. Oh haha, there’s actually a UI for that! There’s a Writing Tools taskbar tray icon, and you can click that and access Settings or About.

3. The next update is going to let you create custom buttons with their own prompt/system prompt, you'll also be able to rearrange the buttons and change the existing ones' system prompts :)

**Comment by beenycool** [comment]
Thank you so much! I was considering purchasing Grammarly, as I couldn't find any other open-source or free alternatives and it was on sale. The only other option I found, Language Tool, was completely inadequate. Plus, I was also concerned about how Grammarly was handling my data. You've saved me some money and a lot of other things! (yes i did use rewrite).

**Comment by theJayTea** [comment]
Thank you for the support, @beenycool !
If you'd like to and are able to, a small donation to support continued development (and my saving up for college haha) would mean the world :'D
