### ISSUE TITLE
Add support for PAC

### ISSUE THREAD

**Issue by darwpm4gs** [theJayTea/WritingTools#79]
as we know not all countries are supported, so we use vpn\proxy. it wound be great to see Proxy auto-config support

**Comment by theJayTea** [comment]
Hello! Unfortunately, an auto-proxy is not something I can add myself (not enough bandwidth and I’m not the most knowledgeable on implementing that).

For now, if Gemini is blocked for you, you can use a local LLM or a multitude of other cloud providers too that serve Llama et al. (oftentimes for free, check out [Cerebras](https://cerebras.ai/blog/introducing-cerebras-inference-ai-at-instant-speed)) for instance!

And of course, a systemwide VPN would be another alternative.

**Comment by theJayTea** [comment]
If you're able to contribute to add this, feel free to open this issue again! Sorry again that i won't be able to implement this right now.
